### ISSUE TITLE
[bug]screen_brightness_ohos 2.1.1 compile fail

### ISSUE THREAD

**Issue by shlowdy** [aaassseee/screen_brightness#75]
screen_brightness_ohos 2.1.1 compile fail

**Comment by aaassseee** [comment]
@shlowdy  Is that only fail when compiling ohos app?

**Comment by aaassseee** [comment]
@ErBWs #71

**Comment by ErBWs** [comment]
@shlowdy  I haven't encountered this problem, maybe you should upgrade your flutter_ohos version? I don't think 3.7 is compatible, 3.22 and above should work.

**Comment by ErBWs** [comment]
https://gitcode.com/openharmony-tpc/flutter_flutter/tree/3.22.0-ohos

Here is the repo for special version of flutter that supports ohos, and instruction down below

**Comment by ErBWs** [comment]
Also the simulator doesn't seems to support brightness adjustment. So it took me a long time to get the latest mate70pro to actually test this plugin and submit the first PR

**Comment by aaassseee** [comment]
@ErBWs I'm encountering this error. Have you faced this issue before?

> hvigor ERROR: Error Cannot find module 'flutter-hvigor-plugin'
Require stack:
- E:\Project\screen_brightness\screen_brightness_ohos\example\ohos\hvigorconfig.ts
- E:\Program Files\Huawei\DevEco Studio\tools\hvigor\hvigor\src\base\internal\lifecycle\init.js
- E:\Program Files\Huawei\DevEco Studio\tools\hvigor\hvigor\src\base\boot\index.js
- E:\Program Files\Huawei\DevEco Studio\tools\hvigor\hvigor\src\base\daemon\cluster\worker-process-lifecycle.js
- E:\Program Files\Huawei\DevEco Studio\tools\hvigor\hvigor\src\base\daemon\process\daemon-process-boot-script.js
> hvigor ERROR: BUILD FAILED in 19 ms

**Comment by ErBWs** [comment]
Looks like you are building with DevEco? It requires to build with flutter toolchain first: use the ohos flutter to `flutter build hap` or use other ide to build

**Comment by aaassseee** [comment]
@ErBWs Yes, I am building with DevEco but after typing the ```flutter build hap```. It shows another error
```
> hvigor ERROR: ENOENT: no such file or directory, scandir 'E:\Project\screen_brightness\screen_brightness_ohos\example\build\ohos\intermediates\flutter\defaultRelease\flutter_assets'
```

**Comment by ErBWs** [comment]
Try use `flutter run --debug -d 127.0.0.1:5555` to directly run the app in simulator. It's weird that I've never met this error before.

Also remember to sign the project before running this cmd. Go to file -> Project Structure, select Signing Configs and check Automatically generate signature

**Comment by aaassseee** [comment]
@shlowdy Can you check after upgrade to 3.22.0. Are there any errors?

**Comment by shlowdy** [comment]
@aaassseee @ErBWs 

screen_brightness_ohos 2.1.0 works.

I use flutter 3.22.1, windows.

doctor info:
lds@DESKTOP-PENHKLG MINGW64 ~
$ flutter doctor
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.22.1-ohos-1.0.4, on Microsoft Windows [版本 10.0.19045.2965], locale zh-CN)
    ! Flutter version 3.22.1-ohos-1.0.4 on channel [user-branch] at C:\Users\lds\Desktop\flutter_flutter


the build info:

> hvigor ERROR: Failed :screen_brightness_ohos:default@HarCompileArkTS... 
> hvigor ERROR: ArkTS Compiler Error
1 ERROR: ArkTS:ERROR File: C:/Users/lds/Desktop/pub_cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/screen_brightness_ohos-2.1.1/ohos/src/main/ets/com/aaassseee/screen_brightness_ohos/stream_handler/BaseStreamHandler.ets:1:21
 Cannot find module '@ohos/flutter_ohos' or its corresponding type declarations.

> More Info: https://developer.huawei.com/consumer/cn/doc/harmonyos-faqs-V5/faqs-compiling-and-building-4-V5


2 ERROR: ArkTS:ERROR File: C:/Users/lds/Desktop/pub_cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/screen_brightness_ohos-2.1.1/ohos/src/main/ets/com/aaassseee/screen_brightness_ohos/stream_handler/BaseStreamHandler.ets:2:42
 Cannot find module '@ohos/flutter_ohos/src/main/ets/plugin/common/EventChannel' or its corresponding type declarations.

> More Info: https://developer.huawei.com/consumer/cn/doc/harmonyos-faqs-V5/faqs-compiling-and-building-4-V5


3 ERROR: ArkTS:ERROR File: C:/Users/lds/Desktop/pub_cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/screen_brightness_ohos-2.1.1/ohos/src/main/ets/com/aaassseee/screen_brightness_ohos/stream_handler/ScreenBrightnessChangedStreamHandler.ets:1:21
 Cannot find module '@ohos/flutter_ohos' or its corresponding type declarations.

> More Info: https://developer.huawei.com/consumer/cn/doc/harmonyos-faqs-V5/faqs-compiling-and-building-4-V5


4 ERROR: ArkTS:ERROR File: C:/Users/lds/Desktop/pub_cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/screen_brightness_ohos-2.1.1/ohos/src/main/ets/com/aaassseee/screen_brightness_ohos/stream_handler/ScreenBrightnessChangedStreamHandler.ets:2:27
 Cannot find module '@ohos/flutter_ohos/src/main/ets/plugin/common/EventChannel' or its corresponding type declarations.

> More Info: https://developer.huawei.com/consumer/cn/doc/harmonyos-faqs-V5/faqs-compiling-and-building-4-V5


5 ERROR: ArkTS:ERROR File: C:/Users/lds/Desktop/pub_cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/screen_brightness_ohos-2.1.1/ohos/src/main/ets/com/aaassseee/screen_brightness_ohos/ScreenBrightnessOhosPlugin.ets:12:8
 Cannot find module '@ohos/flutter_ohos' or its corresponding type declarations.

> More Info: https://developer.huawei.com/consumer/cn/doc/harmonyos-faqs-V5/faqs-compiling-and-building-4-V5


COMPILE RESULT:FAIL {ERROR:6}
> hvigor ERROR: BUILD FAILED in 23 s 289 ms 
ProcessException: The command failed with exit code 1
  Command: hvigorw --mode module -p module=ali_auth_ohos@default,app_link_ohos@default,audio_session@default,auto_orientation@default,battery_state_ohos@default,connectivity_plus@default,device_identifier_ohos@default,device_info_plus@default,file_picker_ohos@default,sqflite@default,image_picker_ohos@default,just_audio_ohos@default,mobile_scanner@default,open_file_ohos@default,package_info_plus@default,path_provider_ohos@default,permission_handler_ohos@default,photo_manager@default,share_plus@default,shared_preferences_ohos@default,umeng_ohos@default,url_launcher_ohos@default,vibration_ohos@default,video_player_ohos@default,volume_controller@default,wakelock_plus_ohos@default,webview_flutter_ohos@default,fluwx@default,screen_brightness_ohos@default,ali_auth_ohos@default,app_link_ohos@default,audio_session@default,auto_orientation@default,battery_state_ohos@default,connectivity_plus@default,device_identifier_ohos@default,device_info_plus@default,file_picker_ohos@default,fluwx@default,image_picker_ohos@default,just_audio_ohos@default,mobile_scanner@default,open_file_ohos@default,package_info_plus@default,path_provider_ohos@default,permission_handler_ohos@default,photo_manager@default,screen_brightness_ohos@default,share_plus@default,shared_preferences_ohos@default,sqflite@default,umeng_ohos@default,url_launcher_ohos@default,vibration_ohos@default,video_player_ohos@default,volume_controller@default,wakelock_plus_ohos@default,webview_flutter_ohos@default -p product=default -p buildMode=debug assembleHar --no-daemon -p FLUTTER_TARGET=C:\Users\lds\Desktop\nas\lib\main.dart -p TARGET_PLATFORM=ohos-arm64 -p DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9mNjM0NGI3NWRjZjg2MWQ4YmYxZjEzMjI3ODBiODgxMWY5ODJlMzFhLw== -p DART_OBFUSCATION=false -p TRACK_WIDGET_CREATION=true -p TREE_SHAKE_ICONS=false -p PACKAGE_CONFIG=C:\Users\lds\Desktop\nas\.dart_tool\package_config.json

**Comment by ErBWs** [comment]
@shlowdy Can you provide full output from `flutter doctor -v`? 

Also check out this [action](https://github.com/ErBWs/Kazumi/actions/runs/16794362982), It build with screen_brightness_ohos 2.1.1 and ohos API19, probably the issue is from DevEco version? Or keep using 2.1.0, 2.1.1 only update the project structure to enable ohos code lint

**Comment by shlowdy** [comment]
@ErBWs 
most be the DevEco issue.

my ide version:
DevEco Studio 5.0.4 Release
Build #DS-233.14475.28.36.5011110
Build Version: 5.0.11.110, built on May 12, 2025
Runtime version: 17.0.12+1-b1087.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  idea.plugins.compatible.build=IC-233.14475.28

what's yours

**Comment by ErBWs** [comment]
DevEco Studio 5.1.1 Release
Build #DS-233.14475.28.36.511820
Build Version: 5.1.1.820, built on June 28, 2025
Runtime version: 17.0.12+1-b1087.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 26.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  idea.plugins.compatible.build=IC-233.14475.28

**Comment by aaassseee** [comment]
@shlowdy Do you still having this problem?

**Comment by ErBWs** [comment]
Please provide `flutter doctor -v`. I think your flutter version is too old, the latest 3.22 version is 1.0.4

**Comment by ErBWs** [comment]
I have no clue. Maybe just use 2.1.0, 2.1.1 is for developers to easily modify the ArkTS code of this plugin with code lint

**Comment by shlowdy** [comment]
updated DevEco Studio to 5.1.1 still the same
I use 2.1.0 now

**Comment by aaassseee** [comment]
@shlowdy @Moyck @ErBWs OK, problem found. When I am using the version 3.22.1-ohos-1.0.1, it did compile fail no matter using the latest IDE. After I upgrade to ohos flutter version 3.27.5-ohos-0.1.0-beta. The problem is gone. Maybe this PR needs to be go with Pre-release version.

**Comment by aaassseee** [comment]
@ErBWs One more thing. Do you know why my Device Manager is gone? 

<img width="404" height="291" alt="Image" src="https://github.com/user-attachments/assets/0447a753-cf0f-4381-a9c0-1d62f00f77b5" />

**Comment by ErBWs** [comment]
> One more thing. Do you know why my Device Manager is gone?

Don't know🤔

I cannot compile no matter version, Looks like it has something wrong with my JAVA runtime.

3.22.0 should work well since the origin PR is merged to 3.22.0

<img width="1496" height="149" alt="Image" src="https://github.com/user-attachments/assets/4c5f04f8-94a8-4f79-8737-6341ea0b38b1" />

**Comment by aaassseee** [comment]
@ErBWs actually you can try with latest 3.22.1-ohos-1.0.1. You can see @shlowdy, @Moyck error when typing flutter build hap

**Comment by ErBWs** [comment]
i've tested with current main branch `br_3.22.0-ohos-1.0.4`, and the example successfully compiled

**Comment by aaassseee** [comment]
@ErBWs Can you switch to 3.22.1-ohos-1.0.1? I think this is the branch which is set by default.

**Comment by ErBWs** [comment]
No it's 1.0.4. Also latest stable version is 1.0.5

<img width="600" height="352" alt="Image" src="https://github.com/user-attachments/assets/9cb29500-a9ea-4de3-bb32-908bc6550879" />

**Comment by aaassseee** [comment]
@shlowdy @Moyck What is your ohos flutter hash ```git rev-parse HEAD```?

**Comment by aaassseee** [comment]
@ErBWs When is this feature implement? After 3.22.1-ohos-1.0.4? Maybe we are using the wrong version. I have tested on 3.22.1-ohos-1.0.1 and it didn't work but the br_3.22.0-ohos-1.0.4 works for me. I might find the version which work and put it to the pubspec flutter version constraint for blocking the unmatched version.

**Comment by ErBWs** [comment]
I don't actually know about the exact version the feature is implemented, and I don't think pubspec flutter version can block specific ohos flutter verison. For the ohos new feature at least 3.22.0 I think

The adoption of ohos flutter is going to last for a long period, so just use the latest stable version of 3.22.0 ohos flutter should work.

Maybe update the changelog, like other packages do:

```
Updates minimum supported SDK version to Flutter 3.22.0-ohos 1.0.4 / Dart 3.4 for ohos.
```

**Comment by aaassseee** [comment]
@ErBWs Sure it can. I am testing on https://gitcode.com/openharmony-tpc/flutter_flutter/tags and found that it compile success at version 3.22.1-ohos-1.0.4 and 3.27.5-ohos-0.0.2. 3.27.5-ohos-0.0.1 and before 3.22.1-ohos-1.0.4 would not work. Sending PR for the version restriction.

**Comment by aaassseee** [comment]
@ErBWs Can you give it a try? https://github.com/aaassseee/screen_brightness/pull/79
